language: java
jdk:
  - oraclejdk7
  - oraclejdk8
install: "mvn --activate-profiles foss-parent-verification --show-version --errors --batch-mode validate dependency:go-offline"
script: "mvn --activate-profiles foss-parent-verification --show-version --errors --batch-mode -Dversions.skip=true clean verify"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - mfriedenhagen@gmail.com
